### ISSUE TITLE
Create DC from MODS when key datastream is MODS

### ISSUE THREAD

**Issue by nate-rcl** [mjordan/islandora_batch_with_derivs#2]
When the key datastream is MODS and no DC record exists in the set of derivatives it would be nice to have the DC generated from the MODS.

**Comment by rosiel** [comment]
Yes, I just came across this too. 
In "normal batch" it is hardcoded, which is evidently not great. https://github.com/Islandora/islandora_batch/blob/3f01d0d1142d9bf33f89b85c0584d956b1dbf21f/includes/islandora_scan_batch.inc#L219 

Perhaps an option to do this?

**Comment by nate-rcl** [comment]
I have made the change in our forked version - I can issue a pull request if you like

**Comment by mjordan** [comment]
I'll take care of this.

**Comment by mjordan** [comment]
@nate-rcl and @rosiel, please test the issue-2 branch. To have your DC datastreams generated from the MODS key datastream, use `islandora_batch_with_derivs_preprocess --key_datastream=MODS --create_dc_from_mods`.

**Comment by nate-rcl** [comment]
Couple of quick questions:

1.  Does anyone know why they hard coded it in batch- does Islandora always need some sort of DC record?

2. Wouldn't it make more sense to create the dc by default  on with an option to turn it off rather than having a flag to create it?  For us it would be a lot easier if this was the case rather than having to remember to add the flag if our key datastream is MODS.  @rosiel what is your typical use case - do you usually have the DC or expect it to be generated off the MODS?

**Comment by mjordan** [comment]
Re. Q1, fedora needs a DC, in fact generates a very basic one (title, identifier) by default. I guess the logic for Islandora is that if there is richer descriptive metadata available, like MODS, copy as.much of it as possible over to the DC.

Re. Q2, yes it does make sense to invert that flag. I'll wait to hear from @rosiel before doing it though.

**Comment by nate-rcl** [comment]
Thanks for the info - sounds great - I will switch over to using the new version from our forked version if that becomes the default

**Comment by rosiel** [comment]
Yes, I think it makes sense to invert the flag (create by default if no DC is provided).

**Comment by nate-rcl** [comment]
That's a good point - what if the flag (which is now inverted) is not set but one of the derivatives is the dc.xml and the user chooses the mods as the key datastream - what should happen - go ahead and overwrite with the data created from the mods or should it be assumed that the existing dc file should be kept?

**Comment by rosiel** [comment]
I think if you're providing a DC, then what you provide should be kept. It should only be generated from MODS if no DC is available.

**Comment by nate-rcl** [comment]
That sounds like a good idea to me

**Comment by mjordan** [comment]
Yes, @rosiel is correct. The basic idea underlying this module is that if there is a file named after a DSID, that file is used to create the datastream.

I've updated the issue-2 branch and it's ready for testing. From the updated README.md:

> If MODS is specified as the value of --key_datastream, the DC datastream that is generated for each object will be generated from the MODS.xml file, which is Islandora's default behavior. If you prefer that a default DC datastream containing only a title and an identifier element be generated, include the --create_dc_from_mods=false option in the islandora_batch_with_derivs_preprocess command (e.g., islandora_batch_with_derivs_preprocess --key_datastream=MODS --create_dc_from_mods=false). If both MODS.xml and DC.xml exist in the object's input directory, both datastreams are populated from the files.

**Comment by mjordan** [comment]
@nate-rcl and @rosiel mind if I merge this branch into 7.x? I'm working on #1 and want to avoid merge conflicts on that one.

**Comment by nate-rcl** [comment]
I haven't had a chance to test it yet  - I will defer to you and @rosiel to make that decision.

**Comment by mjordan** [comment]
@rosiel, OK to merge? I'm not too worried about additional testing.

**Comment by mjordan** [comment]
@rosiel I'd love to merge this. OK with you?

**Comment by rosiel** [comment]
Yes! Sorry I forgot to reply last week.

**Comment by mjordan** [comment]
OK, great, thanks.
