### ISSUE TITLE
Use specified content models when set

### ISSUE THREAD

**Issue by nate-rcl** [mjordan/islandora_batch_with_derivs#6]
It looks like if I specify the optional content model it is not used if the file type is identified in the list in the function islandora_batch_with_derivs_get_cmodel when processing the files.

This becomes an issue when I want to ingest a specific cmodel type like islandora:oralhistoriesCModel which can take a video(MP4/MOV) or Audio as a the OBJ file.

Would there be a way to use the set content model as the specified one instead of using the file type?

**Comment by mjordan** [comment]
@nate-rcl can you provide a sample command that includes all the parameters you would expect to provide?

**Comment by nate-rcl** [comment]
Hi @mjordan 

Here is the command I executed:

drush -v -u 1 islandora_batch_with_derivs_preprocess --key_datastream=MODS --scan_target=/ingest-folder --namespace=ur --parent=parent-pid --content_models=islandora:oralhistoriesCModel

I expected the content models to be islandora:oralhistoriesCModel but they were the islandora:sp_videoCModel. I expected once I specified a model that model would be used for all ingested material.

**Comment by mjordan** [comment]
Thanks, I'll take a look.

**Comment by mjordan** [comment]
@nate-rcl I'm working on this.

**Comment by nate-rcl** [comment]
@mjordan cool - thanks!

**Comment by mjordan** [comment]
OK, please test the issue-6 branch.

**Comment by nate-rcl** [comment]
ok cool - thanks - I'll try and get this on our dev machine today and see if we can test

**Comment by nate-rcl** [comment]
@mjordan I can confirm this worked for me on our test system and Thanks for making the change! 

Should I use this branch on our production system or do you think you will be merging it soon?

Best,
-Nate

**Comment by mjordan** [comment]
Sweet, thanks for testing. I just merged so you should use the 7.x branch.
